feat(windows) - pre push hooks

diff --git a/.git-templates/hooks/pre-push b/.git-templates/hooks/pre-push
--- a/.git-templates/hooks/pre-push
+++ b/.git-templates/hooks/pre-push
@@ -13,9 +13,25 @@ for DIR in $CHECK_DIRECTORIES; do
     fi
 done
 
+sleep_arg=$1
+function exit_delay() {
+    # on Windows, the file is opened in a separate window, so to avoid auto-closing
+    if [ "$sleep_arg" == "--sleep" ]; then
+        sleep 999
+    fi
+    exit $1
+}
+
+function check_exit_status() {
+    if [ $1 -ne 0 ]; then
+        echo "$2 : Linting failed, check the files..."
+        exit_delay 1
+    fi
+}
+
 if [ "$HAS_RELEVANT_CHANGES" = "false" ]; then
     echo "No relevant changes, skipping checks..."
-    exit 0
+    exit_delay 0
 fi
 
 # Lint TS files
@@ -27,29 +43,15 @@ if [ "$MODIFIED_TS_FILES" != "" ]; then
     eslint $MODIFIED_TS_FILES
     ESLINT_EXIT_CODE=$?
 fi
-
-if [ $ESLINT_EXIT_CODE -ne 0 ]; then
-    echo "ESLint failed, check the TypeScript files..."
-    exit $ESLINT_EXIT_CODE
-fi
+check_exit_status $ESLINT_EXIT_CODE "ESLint"
 
 # Run python linting
-ruff ./python/ccxt
-PYTHON_EXIT_CODE=$?
-
-if [ $PYTHON_EXIT_CODE -ne 0 ]; then
-    echo "Python linting failed, check the Python files..."
-    exit $PYTHON_EXIT_CODE
-fi
+npm run check-python-ruff
+check_exit_status $? "Python"
 
 # Run PHP linting
 npm run check-php-syntax
-PHP_EXIT_CODE=$?
-
-if [ $PHP_EXIT_CODE -ne 0 ]; then
-    echo "PHP linting failed, check the PHP files..."
-    exit $PHP_EXIT_CODE
-fi
+check_exit_status $? "PHP"
 
 echo "All checks passed, pushing..."
-exit 0
+exit_delay 0
