update pre-push script

diff --git a/.git-templates/hooks/pre-push b/.git-templates/hooks/pre-push
--- a/.git-templates/hooks/pre-push
+++ b/.git-templates/hooks/pre-push
@@ -22,6 +22,7 @@ fi
 # Lint TS files
 MODIFIED_TS_FILES=$(git diff --name-only upstream/master -- 'ts/**/*.ts')
 
+ESLINT_EXIT_CODE=0
 # Run eslint on the modified files
 if [ "$MODIFIED_TS_FILES" != "" ]; then
     eslint $MODIFIED_TS_FILES
@@ -29,14 +30,31 @@ fi
 
 ESLINT_EXIT_CODE=$?
 
+if [ "$ESLINT_EXIT_CODE" != "0" ]; then
+    echo "ESLint failed, check the TypeScript files..."
+    exit $ESLINT_EXIT_CODE
+fi
+
 # Run python linting
 ruff ./python/ccxt
 
 PYTHON_EXIT_CODE=$?
+
+if [ "$PYTHON_EXIT_CODE" != "0" ]; then
+    echo "Python linting failed, check the Python files..."
+    exit $ESLINT_EXIT_CODE
+fi
+
 
 # Run PHP linting
 npm run check-php-syntax
 
 PHP_EXIT_CODE=$?
 
-exit $((ESLINT_EXIT_CODE + PYTHON_EXIT_CODE + PHP_EXIT_CODE))
+if [ "$PHP_EXIT_CODE" != "0" ]; then
+    echo "PHP linting failed, check the PHP files..."
+    exit $ESLINT_EXIT_CODE
+fi
+
+echo "All checks passed, pushing..."
+exit 0
